<?php  

define("PAGINAR",20);

define("TAMANIOTHUMB",120);
define("TAMANIOTHUMBXL",420);

define("CANTIDADPAGINADO",12);


define("CARPETA_SERVIDOR_MULTIMEDIA","multimedia/");
define("CARPETA_SERVIDOR_MULTIMEDIA_FISICA",DIR_ROOT.CARPETA_SERVIDOR_MULTIMEDIA);

define("CARPETA_SERVIDOR_MULTIMEDIA_ORIGINALES","N/");
define("CARPETA_SERVIDOR_MULTIMEDIA_THUMBS","Thumbs/");
define("CARPETA_SERVIDOR_MULTIMEDIA_THUMBSXL","ThumbsXL/");

define("CARPETA_SERVIDOR_MULTIMEDIA_TMP","tmp/");
define("CARPETA_SERVIDOR_MULTIMEDIA_TMP_FISICA",CARPETA_SERVIDOR_MULTIMEDIA_FISICA.CARPETA_SERVIDOR_MULTIMEDIA_TMP);

define("CARPETA_SERVIDOR_MULTIMEDIA_NOTICIAS","noticias/");

define("DOMINIO_SERVIDOR_MULTIMEDIA","/multimedia/");
define("DOMINIOGENERAL",DOMINIOPORTAL.RAIZPORTAL);
define("DOMINIOWEB",DOMINIOPORTAL.RAIZPORTAL);

define("PUBLICA",DOCUMENT_ROOT."/public/");

define("DOMINIORAIZSITE","/");

define("CLAVEENCRIPTACION","dDtp2d$23#43");

define("PUBLICKEYCAPTCHA","6LeARRsUAAAAAJ-pveqzhd4cdkCB6t089hrK1TI5");
define("PRIVATEKEYCAPTCHA","6LeARRsUAAAAAPgNXfAWlKyu5ra4wVAMbi7H15-G");

define("CARPETA_SERVIDOR_MULTIMEDIA_ALBUM","ALBUM/");

/*CONFIGURACION DE MAIL SALIENTE*/
//ENVIAREMAIL 1 - SI
//ENVIAREMAIL 0 - NO
define("ENVIAREMAIL",'1');
define("EMAIL_FROMNAME","Plan de Gobierno GCBA");
define("EMAIL_FROM","baogp@buenosaires.gob.ar");
define("SMTP","1");
define("SMTP_HOST","smtp.buenosaires.gob.ar");
define("SMTP_USER","baogp@buenosaires.gob.ar");
define("SMTP_PASSW","I6_s9wby");
define("SMTP_PORT","25");
define("SMTP_SSL","0");
define("SMTP_TLS","1");

define("PLANTILLAINTERNA","13");

define("YOUTUBE_EMBED","https://www.youtube.com/embed/");

?>